//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BarcodeJournal
    {
        public string ControllerName { get; set; }
        public int EntryID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string BinLocationCode { get; set; }
        public string BlendingInstructionCode { get; set; }
        public string ShortName { get; set; }
    }
}
