//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class GoodsReceiptBarcodeAvailable
    {
        public int GoodsReceiptID { get; set; }
        public int GoodsReceiptDetailID { get; set; }
        public string GoodsReceiptReference { get; set; }
        public System.DateTime GoodsReceiptEntryDate { get; set; }
        public int BatchID { get; set; }
        public System.DateTime BatchEntryDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string SealCode { get; set; }
        public string BatchCode { get; set; }
        public string LabCode { get; set; }
        public string Barcode { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int BinLocationID { get; set; }
        public string BinLocationCode { get; set; }
        public decimal UnitWeight { get; set; }
        public decimal TareWeight { get; set; }
        public Nullable<decimal> QuantityAvailables { get; set; }
        public bool Approved { get; set; }
        public bool LabApproved { get; set; }
        public bool LabHold { get; set; }
        public bool LabInActive { get; set; }
        public string LabInActiveCode { get; set; }
    }
}
