//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class GoodsReceiptPendingPurchasing
    {
        public int GoodsReceiptTypeID { get; set; }
        public string PurchaseOrderCodes { get; set; }
        public string CustomerOfficialNames { get; set; }
        public string Description { get; set; }
    }
}
