//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class InventoryControl
    {
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public string CategoryName { get; set; }
        public string SalesUnit { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<int> BinLocationCode { get; set; }
        public Nullable<int> EntryDate { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> SealCode { get; set; }
        public Nullable<int> BatchCode { get; set; }
        public Nullable<int> LabCode { get; set; }
        public Nullable<int> Barcode { get; set; }
        public Nullable<int> ProductionDate { get; set; }
        public Nullable<int> ExpiryDate { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<decimal> BisQuantity { get; set; }
        public Nullable<decimal> BisQuantityIssued { get; set; }
        public Nullable<decimal> BisQuantityRemains { get; set; }
        public Nullable<decimal> QuantityAvailableArrivals { get; set; }
        public Nullable<decimal> QuantityAvailableLocation1 { get; set; }
        public Nullable<decimal> QuantityAvailableLocation2 { get; set; }
    }
}
