//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class InventoryControl
    {
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public string CategoryName { get; set; }
        public string SalesUnit { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public string BinLocationCode { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Code { get; set; }
        public string SealCode { get; set; }
        public string BatchCode { get; set; }
        public string LabCode { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool Approved { get; set; }
        public decimal BisQuantity { get; set; }
        public decimal BisQuantityIssued { get; set; }
        public decimal BisQuantityRemains { get; set; }
        public decimal QuantityAvailableArrivals { get; set; }
        public decimal QuantityAvailableLocation1 { get; set; }
        public decimal QuantityAvailableLocation2 { get; set; }
    }
}
