//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class SemifinishedRecyclatePendingWorkshift
    {
        public int SemifinishedProductWorkshiftID { get; set; }
        public int SemifinishedProductShiftID { get; set; }
        public System.DateTime SemifinishedProductEntryDate { get; set; }
        public Nullable<decimal> TotalQuantityRemains { get; set; }
    }
}
