//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class TransferOrderPendingBlendingInstruction
    {
        public int CommodityID { get; set; }
        public Nullable<decimal> QuantityRemains { get; set; }
        public Nullable<decimal> QuantityTransferOrders { get; set; }
        public Nullable<decimal> QuantityAvailableL2 { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public string OfficialCode { get; set; }
        public Nullable<int> CommodityTypeID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    }
}
